### ISSUE TITLE
Something went wrong with semantic-release

### ISSUE THREAD

**Issue by olvidalo** [eXist-db/gulp-exist#14] opened 2018-07-05 09:59 UTC
There was no new version released after merging #13 and a successful CI run. It didn't seem to see the fix and breaking commits.

```
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOCHANGE There are no relevant changes, so no new version is released.
```

I've updated semantic-release to the latest version and it released a patch version. So I guess the commits from the merge were just skipped. 

any ideas maybe @line-o? make a breaking dummy commit?

**Comment by line-o** [comment] 2018-07-05 10:15
@olvidalo hmm, the changes do not seem to be that breaking after all :)
Did the update in fact fix the issue or cause it?

**Comment by line-o** [comment] 2018-07-05 10:15
Do you know the cause, is what really interests me?

**Comment by olvidalo** [comment] 2018-07-05 13:26
I have no clue what caused it, and I hoped an update would magically fix it, which it did in a sense. It just forgot the commits inbetween.

The changes are indeed not that breaking but still a little breaking :/

I installed gulp@3.9.1 using npm-install-version and made test.js use that version. Almost all ran through except for two, and they were both related to this change: 
https://github.com/olvidalo/gulp-exist/commit/b9619bf90ff1a04c51189cebec0e060eb18bdc58#diff-168726dbe96b3ce427e7fedce31bb0bcL175 (index.js 175)

The timestamp doesn't get appended to the xquery output file name.

We could try to find a backward compatible way to do this but I'd be tempted just leave it in and tell the world its breaking using a dummy commit. 

I should also unpublish the current npm package too so the one or two people using this feature people don't get the update unknowingly, but I don't now if that wouldn't confuse semantic-release again.

**Comment by line-o** [comment] 2018-07-06 10:32
@olvidalo you should create a new separate issue for that timestamp thing.

**Comment by line-o** [comment] 2018-07-09 09:00
@olvidalo did you unpublish 1.4.3?
I learned, that the breaking keyword needs to be in the body of a commit message in order to be picked up by semantic-release.

**Comment by olvidalo** [comment] 2018-07-09 17:02
Yup, it's unpublished,

> @olvidalo you should create a new separate issue for that timestamp thing.

Not sure. I mean if we mark the release as breaking, there's no need to resolve it, or is there?
I suspect that there's an issue with the file objects resulting from different vinyl versions. And who knows what else there might break in exotic setups.

**Comment by line-o** [comment] 2018-07-10 12:54
Since 2.0.0 is out (💯👍) we should close this issue.

**Closed as completed by line-o** 2018-07-10 12:54 UTC
